#include<stdio.h>
main()
{
	printf("---------\n");
	printf("|\t|\n");
	printf("K\t|\n");
	printf("R\t|\n");
	printf("I\t|\n");
	printf("S\t|\n");
	printf("H\t|\n");
	printf("A\t|\n");
	printf("|\t|\n");
	printf("---------\n");
}
